version: '2'

services:

  artemis:
    image: vromero/activemq-artemis
    container_name: activemq
    ports:
      - "8161:8161"
      - "61616:61616"
      - "5672:5672"
    environment:
      ARTEMIS_USERNAME: quarkus
      ARTEMIS_PASSWORD: quarkus